### ISSUE TITLE
Custom Components support

### ISSUE THREAD

**Issue by Rafaesp** [mvysny/karibu-dsl#1]
Hi! Awesome project.
It would be great if it supported the ability to use CustomComponents created as a composition of others components. Is it possible already? If it is, it needs and example.

Thanks!

**Comment by mvysny** [comment]
Thank you, that is true - there is no extension method which would create a CustomComponent like this:

```kotlin
customComponent {
  verticalLayout {
    ...
  }
}
```
However, that is on purpose:

I believe that CustomComponent is only used to implement your own components, usually by extending the CustomComponent and setting the composition root. You can learn more here: https://vaadin.com/docs/-/part/framework/components/components-customcomponent.html

In this case it would be pointless for Karibu to actually introduce the `customComponent{}` extension method, because that creates no class you could extend.
Instead, what you should do is to introduce your own extension method. Just implement your component, say, `MyComposite`, and then you just write the following code below your component:

```kotlin
fun HasComponents.myComposite(block: MyComposite.()->Unit = {}) = init(MyComposite(), block)
```

This will allow you to use your component as follows:
```kotlin
verticalLayout {
  myComposite {
    styleName = "black"; w = 100.perc;
    ... // etc
  }
}
```

I definitely need to add this to the documentation though - good catch!

If you believe that I still should introduce the `customComponent{}` extension method, please add your use case, so that we can discuss.

**Comment by mvysny** [comment]
Added the documentation regarding custom components to the project page.

**Comment by Rafaesp** [comment]
That example is exactly what I needed. Thanks! You can close this issue when you want.

**Comment by mvysny** [comment]
Thanks. Since the documentation is updated, closing the issue.

**Comment by mvysny** [comment]
It's better to use Composite; related issue #12
