### ISSUE TITLE
Version 0.70 compatibility

### ISSUE THREAD

**Issue by vlipovetskii** [mvysny/karibu-dsl#19]
Hi, Martin

Is version 0.70 compatible with Vaadin 13.x ?

**Comment by mvysny** [comment]
It should be, but there are two things:

1. The AppLayout has been changed from scratch in Vaadin 14 and Karibu-DSL 0.7 followed Vaadin 14 API. So if you need to use AppLayout with Vaadin 13, you will have to use Karibu-DSL 0.6.x
2. There is no MenuBar in Vaadin 13, so that one will only work with Vaadin 14.

Apart from that, Karibu-DSL 0.7 should be compatible with Vaadin 13. But if you find out otherwise, just let me know.
