### ISSUE TITLE
Binder spec to allow non-null properties on POJO

### ISSUE THREAD

**Issue by luistrigueiros** [mvysny/karibu-dsl#2]
Can you please add support for non-null properties in the binder spec.
In the link bellow is an example where I have not been able to defined the binder without having to make the pojo properties nullable.

https://gist.github.com/luistrigueiros/97c989d56fa74cfcdbac0f46eeb9d7c2

Thank you, kindly
   Luis Oscar

**Comment by mvysny** [comment]
Sure thing, thanks for letting me know!

**Comment by mvysny** [comment]
Actually the Flow (Vaadin 10) DSL should have the `bindN` function which allows for non-null property binding. I named it `bindN` to avoid collisions with `bind` since Kotlin compiler sometimes complained that it can't choose between the two. Please feel free to review, try it out and let me know ;) Meanwhile I'll fix this for v8.

**Comment by mvysny** [comment]
The fix should be present in Karibu-DSL 0.2.12, both for Vaadin 8 and for Vaadin 10. You should be able to write something like this, for the `description` field of type `String`:
```kotlin
bind(binder).bindN(Process::description)
```
Please let me know whether this works for you.

**Comment by luistrigueiros** [comment]
Cool thanks I can't wait to check it.
