### ISSUE TITLE
Proposal: Additional id: String parameter

### ISSUE THREAD

**Issue by vlipovetskii** [mvysny/karibu-dsl#30]
I leverage setId(...) with Vaadin components, to simplify identifying them with the karibu-testing _get<...> { id = ... } methods.

So my code looks like
button(...) { setId(...) ... }.

If to add to all dsl component methods 
id: String? = null, ...
and if (id != null) setId(id)

the code will be a bit more clean
 button(..., id = ...) {
... }

**Comment by mvysny** [comment]
Hmmm, it is a bit of a breaking change, but I definitely agree there is a lot of merit in having the components properly addressable by their IDs. I'll experiment a bit and I'll try to add the ID as an optional last parameter to every DSL function, and let's see what will break :-D

**Comment by mvysny** [comment]
Just a quick question: for me usually looking up a component by its class and caption/label/text is enough. Could you describe your use-case which requires to set the ID?

I'm thinking that the DSL functions should only expose the most important properties of any given component, leaving other properties to be set in the DSL block itself. That's why the `className` nor `styles` are not exposed via the DSL. And since the ID property is "only" used for testing, I'm actually leaning towards leaving the ID out.

**Comment by vlipovetskii** [comment]
You are right. It's better to leave id out of the dsl functions and don't pollute the functions.

I have a multi-language support for all text properties of the components. Id provides language independant and robust way to search the components.

**Comment by mvysny** [comment]
> I have a multi-language support for all text properties of the components. Id provides language independant and robust way to search the components.

True, that is an excellent use-case. Yet, I agree that we should probably not pollute the DSL functions; therefore I'm hesitantly closing this as won't fix.

You might be able to keep the code base a bit cleaner by using the `id_ = "foo"` syntax, but it's only a minor improvement:

```kotlin
public var Component.id_: String?
    get() = id.orElse(null)
    set(value) {
        setId(value)
    }
```
This is currently only present in Karibu-Testing; however if you would find this useful in Karibu-DSL as well, just let me know and I'll add this to Karibu-DSL as well.
