### ISSUE TITLE
Test fails with the new api openDialog 

### ISSUE THREAD

**Issue by vlipovetskii** [mvysny/karibu-dsl#74]
```
@VaadinDsl
public fun (@VaadinDsl HasComponents).dialog(block: (@VaadinDsl Dialog).() -> Unit = {}): Dialog
        = init(Dialog(), block)
```
New api doesn't add (inside init) Dialog component to HasComponents
```
public fun openDialog(block: (@VaadinDsl Dialog).() -> Unit = {}): Dialog {
    val dlg = Dialog()
    dlg.open()
    dlg.block()
    return dlg
}
```

As a result, karibu-testing fails with error: 
> No visible Dialog in CustomerAppLayout[] matching Dialog: []. Component tree:

Vaadin 24.5.8, karibu-dsl 2.2.0, karibu-tools 0.23

I've got two suggestions:
**1)** This an error in a new api. 
Resolution
```
@VaadinDsl
public fun (@VaadinDsl HasComponents).openDialog(block: (@VaadinDsl Dialog).() -> Unit = {}): Dialog {
    val dlg = init(Dialog(), block)
    dlg.open()
    return dlg
}

```  
With the code above test is successfull.

**2)** It's necessary to adjust karibu-tools to support the openDialog api without HasComponents.

P.S. Replacement dialog with openDialog is a breaking change. It would be better to leave dialog api for a couple versions and mark it as @Deprecated.

**Comment by mvysny** [comment]
Yup, the fault is on my side. Since `Dialog` is `Component`, it can technically be inserted anywhere into the component tree; but the Dialog doesn't work that way - it instead attaches itself to the UI when Dialog.open() is called. I haven't realized that and mechanically created the `dialog{}` DSL function. Now I realized that the function has no sensible use, and the best way would be to delete it. Usually a dialog is created by creating a class which extends `Dialog`; alternatively if the dialog code is short you can use the `openDialog()` global function.

I don't think that anyone used the `dialog{}` function since it was broken from the beginning, so I think it should be safe to delete. However, deprecating it is a better idea. Let me do that.

EDIT: ah I deleted the function already.

**Comment by mvysny** [comment]
Hmm, however the `openDialog{}` function does add the dialog to the tree (via the `open()` method); at least I'd swear there are tests for that. Let me check.

**Comment by mvysny** [comment]
Yeah, this test code works for me well:
```kotlin
        @Test fun smoke() {
            openDialog()
            _expectOne<Dialog>()
        }
```
Karibu-DSL 2.2.0. Does this work for you too?

**Comment by mvysny** [comment]
Ah, now I understand, you're trying to add the Dialog inside of a layout CustomerAppLayout: `No visible Dialog in CustomerAppLayout[] matching Dialog: []. Component tree:`

The Dialog doesn't work that way - it adds itself to UI.getCurrent() when you call dialog.open(). This gets trickier when you have multiple modal dialogs - then the newest modal dialog adds itself to the last modal dialog (I think); the point is that the Dialog will insert itself correctly somewhere into the UI so that the modality curtain works correctly server-side; the point is that the Dialog will insert itself into the UI somewhere, it's not up to us to decide where the Dialog gets inserted. That's why the old `HasComponents.dialog{}` DSL didn't make any sense and was removed.

**Comment by vlipovetskii** [comment]
Thank you for detailed explanation!

I have replaced in my test 
`dialog `should be equal to` _get()`
with
`dialog `should be equal to` currentUI._get()`
in order to use UI instead of CustomerAppLayout 
and now naturally the test finishes with success.
